"""Regenerate ``fdb_scraper/generated/vocab.py`` from an extracted export.

The codes come from the programme files, the German labels from the export's own
label bundle (``_config/ResourceBundleEntries/Labels``), so nothing is typed by
hand. Run after an export whose validation flagged an unknown category:

    uv run python scripts/gen_vocab.py data/foerderprogramme_export
"""

from __future__ import annotations

import html
import re
import sys
from pathlib import Path
from xml.etree import ElementTree as ET

import polars as pl

from fdb_scraper.parser import strip_html
from fdb_scraper.process import decode
from fdb_scraper.schema import USEABLE_FIELDS
from fdb_scraper.scraper import scrape

TD_RE = re.compile(r"<td>(.*?)</td>", re.DOTALL)

LABELS_SUBDIR = "BMWI/_config/ResourceBundleEntries/Labels"
# Subordinate funding areas keep their labels in a separate bundle, and a few
# codes (e.g. messen_ausstellungen) exist in both with different wording.
UF_BUNDLE = "FDB/UntergeordneteFoerderbereiche"
MAIN_BUNDLE = "FDB"


def german_label(path: Path) -> str | None:
    """German cell of the label's de/en table, falling back to its description."""
    root = ET.parse(path).getroot()
    for prop in root.findall("property"):
        if prop.get("name") != "gsb:value":
            continue
        text = prop.find("text")
        if text is None or not text.text:
            break
        tds = [strip_html(td) for td in TD_RE.findall(html.unescape(text.text))]
        # Cells 0 and 1 are the language header ("de", "en"); 2 and 3 the values.
        if len(tds) >= 3 and tds[0] == "de":
            return tds[2]
    for prop in root.findall("property"):
        if prop.get("name") == "gsb:description":
            return strip_html(_value_of(prop))
    return None


def _value_of(prop: ET.Element) -> str | None:
    v = prop.find("value")
    return v.text if v is not None else None


def main(export_dir: str) -> None:
    root = Path(export_dir)
    labels_root = root / LABELS_SUBDIR

    df = decode(scrape(USEABLE_FIELDS, export_dir=root))
    closed = [
        c
        for c, dtype in df.schema.items()
        if dtype == pl.List(pl.String)
        and c not in {"foerderorganisation", "kontakt", "externer_link"}
    ]

    lines = [
        '"""Closed vocabularies of the Förderdatenbank export, code -> German label.',
        "",
        "Generated by ``scripts/gen_vocab.py`` from an extracted export, then",
        "committed so any upstream change to a category list shows up as a reviewable",
        "diff. Codes are kept verbatim -- including upstream oddities such as",
        "``_bundesweit`` alongside ``bundesweit`` and the ``schlesig_holstein`` typo --",
        "so validation stays honest about what the source actually said. A ``None``",
        "label means the export ships no label entry for that code.",
        '"""',
        "",
    ]
    unlabelled = []
    for field in sorted(closed):
        codes = sorted(set(df[field].explode().drop_nulls().to_list()))
        bundle = UF_BUNDLE if field.startswith("uf_") else MAIN_BUNDLE
        lines.append(f"{field.upper()} = {{")
        for code in codes:
            candidates = [labels_root / bundle / f"{code}.xml", *labels_root.rglob(f"{code}.xml")]
            label = next(
                (german_label(p) for p in candidates if p.is_file()),
                None,
            )
            if label is None:
                unlabelled.append(f"{field}/{code}")
                lines.append(f'    "{code}": None,')
            else:
                lines.append(f'    "{code}": "{label}",')
        lines += ["}", ""]

    lines.append("CLOSED_VOCABS = {")
    lines += [f'    "{f}": {f.upper()},' for f in sorted(closed)]
    lines += ["}", ""]

    out = Path(__file__).parent.parent / "src" / "fdb_scraper" / "generated" / "vocab.py"
    out.write_text("\n".join(lines))
    print(f"{out}: {len(closed)} vocabularies")
    if unlabelled:
        print(f"no label in the export for {len(unlabelled)}: {unlabelled}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "data/foerderprogramme_export")
