"""Regenerate ``fdb_scraper/generated/contract_data.py`` from an extracted export.

Records, per document type, which properties exist and what container each one
declares. Run after a contract failure that turns out to be a legitimate
upstream change, then review the diff:

    uv run python scripts/gen_contract.py data/foerderprogramme_export
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

from fdb_scraper.links import CONTENT_DIR
from fdb_scraper.scraper import parse_xml

OUT = Path(__file__).parent.parent / "src" / "fdb_scraper" / "generated" / "contract_data.py"

HEADER = '''"""Recorded structure of the export, per document type.

Generated by ``scripts/gen_contract.py`` and committed so that any upstream
change to the document format shows up as a reviewable diff. Consumed by
``fdb_scraper.contract``.
"""

# Property container -> the child element it must carry.
PROPERTY_CHILD = {'''


def main(export_dir: str) -> None:
    content = Path(export_dir) / CONTENT_DIR
    if not content.is_dir():
        raise FileNotFoundError(content)

    documents: dict[str, dict[str, str]] = defaultdict(dict)
    children: dict[str, set[str]] = defaultdict(set)
    totals: dict[str, int] = defaultdict(int)

    for path in content.rglob("*.xml"):
        root = parse_xml(path)
        doc_type = root.get("type")
        totals[doc_type] += 1
        for prop in root.findall("property"):
            name, declared = prop.get("name"), prop.get("type")
            recorded = documents[doc_type].get(name)
            if recorded is not None and recorded != declared:
                raise SystemExit(
                    f"{name} is both {recorded} and {declared} in {doc_type} ({path});"
                    " the contract assumes one container per property name"
                )
            documents[doc_type][name] = declared
            children[declared] |= {c.tag for c in prop}

    lines = [HEADER]
    for declared, tags in sorted(children.items()):
        if len(tags) != 1:
            raise SystemExit(f"{declared} carries more than one child element: {sorted(tags)}")
        lines.append(f'    "{declared}": "{next(iter(tags))}",')
    lines += ["}", "", "DOCUMENTS = {"]
    for doc_type, properties in sorted(documents.items()):
        lines.append(f'    # {totals[doc_type]} documents in the export')
        lines.append(f'    "{doc_type}": {{')
        lines += [f'        "{n}": "{t}",' for n, t in sorted(properties.items())]
        lines.append("    },")
    lines += ["}", ""]

    OUT.write_text("\n".join(lines))
    print(f"{OUT}: {len(documents)} document types, {sum(totals.values())} documents")
    for doc_type, properties in sorted(documents.items()):
        print(f"  {doc_type:24} {totals[doc_type]:5} documents, {len(properties)} properties")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "data/foerderprogramme_export")
